name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Debug information
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pillow
        # Note: We're not installing heavy dependencies like torch and diffusers
        # since they're not needed for basic tests and slow down CI
        
    - name: Test with pytest
      run: |
        pytest tests/ -v  # Added -v for verbose output
